#!/usr/bin/env bash
# Script that pings an IP address passed as an argument

# IP variable
IP="${1}"

# Filename variable
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
	    echo "Usage: ${fn} {IP_ADDRESS}"
    else
	        ping -c 5 "${IP}"
fi
