#!/usr/bin/env bash
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
useradd -r nginx || true
pkill -u www-data nginx
nginx -g 'daemon off;'